name: Core.Solyanka.Utils

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      PROJ_DIR: src/Core/Solyanka.Utils/
      PROJ: ${{ env.PROJ_DIR }}/Solyanka.Utils.csproj

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJ }}
      
    - name: Build
      run: dotnet build ${{ env.PROJ }} --no-restore -c Release
      
    - name: Pack
      run: dotnet pack ${{ env.PROJ }} --no-build
      
    - name: Push
      run: dotnet nuget push ${{ env.PROJ_DIR }}/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate --no-symbols
